### ISSUE TITLE
Proposta: aggiungere qualche file al .gitignore

### ISSUE THREAD

**Issue by jacquerie** [subotto/subtracker#4]
Probabilmente c'è una buona ragione per cui `database_url` e `test.sqlite` non sono nel `.gitignore`, ma ogni tanto mi sfugge un `git add .` di troppo. È possibile aggiungerli?

Mi piacerebbe poi aggiungere una directory `subtracker` al `.gitignore`: è la directory che uso come Virtualenv per le dipendenze. Sarebbe ok?

Ciao,
Pino

**Comment by giomasce** [comment]
Fatta la prima parte. Giusto per evitare nomi troppo comuni (che potrebbero andare in conflitto con l'uso che ne fanno altri), potresti rinominare la directory di virtualenv in qualcosa dipo `virtualenv` o `venv`, così è più chiaro cosa rappresenta quella riga nel `.gitignore`?
